/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bd1.gestoridentidades;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author belu_
 */
public class ReseteoContraseña extends javax.swing.JFrame {

    /**
     * Creates new form ReseteoContraseña
     */
    public ReseteoContraseña() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlReseteoContra = new javax.swing.JPanel();
        lblResetear = new javax.swing.JLabel();
        txtRespuesta = new javax.swing.JTextField();
        lblRespuesta = new javax.swing.JLabel();
        lblPregunta = new javax.swing.JLabel();
        lblUsuario2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnMostrarPregunta1 = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        pnlNuevaContraseña = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlReseteoContra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblResetear.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblResetear.setText("Resetear Contraseña");
        pnlReseteoContra.add(lblResetear, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 36, -1, -1));

        txtRespuesta.setToolTipText("Ingrese respuesta");
        txtRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespuestaActionPerformed(evt);
            }
        });
        pnlReseteoContra.add(txtRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 211, 30));

        lblRespuesta.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblRespuesta.setText("Respuesta");
        pnlReseteoContra.add(lblRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        lblPregunta.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        pnlReseteoContra.add(lblPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 420, 40));

        lblUsuario2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblUsuario2.setText("Usuario");
        pnlReseteoContra.add(lblUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        txtUsuario.setToolTipText("Ingrese nombre de usuario");
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        pnlReseteoContra.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 211, 30));

        btnMostrarPregunta1.setText("Mostrar Pregunta");
        btnMostrarPregunta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarPregunta1ActionPerformed(evt);
            }
        });
        pnlReseteoContra.add(btnMostrarPregunta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        pnlReseteoContra.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 304, -1, -1));

        jLabel1.setText("Nueva Contraseña");

        jLabel2.setText("Repita Nueva Contraseña");

        jButton1.setText("jButton1");

        javax.swing.GroupLayout pnlNuevaContraseñaLayout = new javax.swing.GroupLayout(pnlNuevaContraseña);
        pnlNuevaContraseña.setLayout(pnlNuevaContraseñaLayout);
        pnlNuevaContraseñaLayout.setHorizontalGroup(
            pnlNuevaContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevaContraseñaLayout.createSequentialGroup()
                .addGroup(pnlNuevaContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNuevaContraseñaLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(pnlNuevaContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlNuevaContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(jTextField1)))
                    .addGroup(pnlNuevaContraseñaLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jButton1)))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        pnlNuevaContraseñaLayout.setVerticalGroup(
            pnlNuevaContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevaContraseñaLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(pnlNuevaContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlNuevaContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jButton1)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(pnlNuevaContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlReseteoContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(pnlNuevaContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlReseteoContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespuestaActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnMostrarPregunta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarPregunta1ActionPerformed
        PersonaConexion pc = new PersonaConexion(conect.obtenerConexion());
        try {
            Persona persona = pc.obtenerPersona(txtUsuario.getText());

            if (persona != null) {
                Pregunta pregunta = new Pregunta(conect.obtenerConexion());
                lblPregunta.setText(pregunta.obtenerPregunta(txtUsuario.getText()));
            } else {
                showMessageDialog(null, "Usuario incorrecto", "Error", ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMostrarPregunta1ActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        try {
            Pregunta pregunta = new Pregunta(conect.obtenerConexion());
            if (pregunta.respuestaCorrecta(txtUsuario.getText(), txtRespuesta.getText())) {
                System.out.println("bien");
                pnlNuevaContraseña.setVisible(true);
                pnlReseteoContra.setVisible(false);
            } else {
                showMessageDialog(null, "Respuesta incorrecta", "Error", ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReseteoContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReseteoContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReseteoContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReseteoContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReseteoContraseña().setVisible(true);
            }
        });
    }

    ConexionBD conect = new ConexionBD();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnMostrarPregunta1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JLabel lblResetear;
    private javax.swing.JLabel lblRespuesta;
    private javax.swing.JLabel lblUsuario2;
    private javax.swing.JPanel pnlNuevaContraseña;
    private javax.swing.JPanel pnlReseteoContra;
    private javax.swing.JTextField txtRespuesta;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
