
package bd1.gestoridentidades;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author belu_
 */
public class ReseteoContraseña extends javax.swing.JFrame {

    /**
     * Creates new form ReseteoContraseña
     */
    public ReseteoContraseña() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frNuevaContraseña = new javax.swing.JFrame();
        pnlNuevaContra = new javax.swing.JPanel();
        lblNuevaContraseña = new javax.swing.JLabel();
        lblNuevaContraseña2 = new javax.swing.JLabel();
        btnConfirmarContraseña = new javax.swing.JButton();
        txtNuevaContraseña = new javax.swing.JPasswordField();
        txtNuevaContraseña2 = new javax.swing.JPasswordField();
        btnConfirmarContraseña1 = new javax.swing.JButton();
        pnlReseteoContra = new javax.swing.JPanel();
        lblResetear = new javax.swing.JLabel();
        txtRespuesta = new javax.swing.JTextField();
        lblRespuesta = new javax.swing.JLabel();
        lblPregunta = new javax.swing.JLabel();
        lblUsuario2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnMostrarPregunta1 = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();

        frNuevaContraseña.setMinimumSize(new java.awt.Dimension(538, 380));
        frNuevaContraseña.setPreferredSize(new java.awt.Dimension(538, 380));
        frNuevaContraseña.setResizable(false);
        frNuevaContraseña.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNuevaContraseña.setText("Nueva contraseña");

        lblNuevaContraseña2.setText("Repita Nueva Contraseña");

        btnConfirmarContraseña.setText("Confirmar");
        btnConfirmarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarContraseñaActionPerformed(evt);
            }
        });

        btnConfirmarContraseña1.setText("Iniciar Sesión");
        btnConfirmarContraseña1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarContraseña1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNuevaContraLayout = new javax.swing.GroupLayout(pnlNuevaContra);
        pnlNuevaContra.setLayout(pnlNuevaContraLayout);
        pnlNuevaContraLayout.setHorizontalGroup(
            pnlNuevaContraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNuevaContraLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(pnlNuevaContraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlNuevaContraLayout.createSequentialGroup()
                        .addGroup(pnlNuevaContraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNuevaContraseña2)
                            .addComponent(lblNuevaContraseña))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlNuevaContraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNuevaContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNuevaContraseña2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlNuevaContraLayout.createSequentialGroup()
                        .addComponent(btnConfirmarContraseña)
                        .addGap(57, 57, 57)
                        .addComponent(btnConfirmarContraseña1)))
                .addGap(108, 108, 108))
        );
        pnlNuevaContraLayout.setVerticalGroup(
            pnlNuevaContraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNuevaContraLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(pnlNuevaContraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevaContraseña)
                    .addComponent(txtNuevaContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pnlNuevaContraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevaContraseña2)
                    .addComponent(txtNuevaContraseña2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(pnlNuevaContraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmarContraseña)
                    .addComponent(btnConfirmarContraseña1))
                .addGap(96, 96, 96))
        );

        frNuevaContraseña.getContentPane().add(pnlNuevaContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlReseteoContra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblResetear.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblResetear.setText("Resetear Contraseña");
        pnlReseteoContra.add(lblResetear, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 36, -1, -1));

        txtRespuesta.setToolTipText("Ingrese respuesta");
        txtRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespuestaActionPerformed(evt);
            }
        });
        pnlReseteoContra.add(txtRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 211, 30));

        lblRespuesta.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblRespuesta.setText("Respuesta");
        pnlReseteoContra.add(lblRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        lblPregunta.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        pnlReseteoContra.add(lblPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 420, 40));

        lblUsuario2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblUsuario2.setText("Usuario");
        pnlReseteoContra.add(lblUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        txtUsuario.setToolTipText("Ingrese nombre de usuario");
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        pnlReseteoContra.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 211, 30));

        btnMostrarPregunta1.setText("Mostrar Pregunta");
        btnMostrarPregunta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarPregunta1ActionPerformed(evt);
            }
        });
        pnlReseteoContra.add(btnMostrarPregunta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        pnlReseteoContra.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 304, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlReseteoContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlReseteoContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespuestaActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnMostrarPregunta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarPregunta1ActionPerformed
        PersonaConexion pc = new PersonaConexion(conect.obtenerConexion());
        try {
            Persona persona = pc.obtenerPersona(txtUsuario.getText());

            if (persona != null) {
                Pregunta pregunta = new Pregunta(conect.obtenerConexion());
                lblPregunta.setText(pregunta.obtenerPregunta(txtUsuario.getText()));
            } else {
                showMessageDialog(null, "Usuario incorrecto", "Error", ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMostrarPregunta1ActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        try {
            Pregunta pregunta = new Pregunta(conect.obtenerConexion());
            if (pregunta.respuestaCorrecta(txtUsuario.getText(), txtRespuesta.getText())) {
                frNuevaContraseña.setVisible(true);
                pnlNuevaContra.setVisible(true);
            } else {
                showMessageDialog(null, "Respuesta incorrecta", "Error", ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnConfirmarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarContraseñaActionPerformed
        String contra = "";
        String contra2 = "";
        for (int i = 0; i < txtNuevaContraseña.getPassword().length; i++) {
            contra += txtNuevaContraseña.getPassword()[i];
        }
        for (int i = 0; i < txtNuevaContraseña2.getPassword().length; i++) {
            contra2 += txtNuevaContraseña2.getPassword()[i];
        }
        if (contra.equals(contra2)) {
            PersonaConexion pc = new PersonaConexion(conect.obtenerConexion());
            try {
                pc.cambiarContraseña(contra, txtUsuario.getText());
                showMessageDialog(null, "Contraseña modificada con éxito", "Éxito", INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                Logger.getLogger(ReseteoContraseña.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            showMessageDialog(null, "Ambas contraseñas deben ser iguales", "Error", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConfirmarContraseñaActionPerformed

    private void btnConfirmarContraseña1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarContraseña1ActionPerformed
        InicioSesion inicioSesion = new InicioSesion();
        inicioSesion.setVisible(true);
        this.setVisible(false);
        frNuevaContraseña.setVisible(false);
    }//GEN-LAST:event_btnConfirmarContraseña1ActionPerformed

    ConexionBD conect = new ConexionBD();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnConfirmarContraseña;
    private javax.swing.JButton btnConfirmarContraseña1;
    private javax.swing.JButton btnMostrarPregunta1;
    private javax.swing.JFrame frNuevaContraseña;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel lblNuevaContraseña;
    private javax.swing.JLabel lblNuevaContraseña2;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JLabel lblResetear;
    private javax.swing.JLabel lblRespuesta;
    private javax.swing.JLabel lblUsuario2;
    private javax.swing.JPanel pnlNuevaContra;
    private javax.swing.JPanel pnlNuevaContraseña;
    private javax.swing.JPanel pnlNuevaContraseña1;
    private javax.swing.JPanel pnlNuevaContraseña2;
    private javax.swing.JPanel pnlNuevaContraseña3;
    private javax.swing.JPanel pnlReseteoContra;
    private javax.swing.JPasswordField txtNuevaContraseña;
    private javax.swing.JPasswordField txtNuevaContraseña2;
    private javax.swing.JTextField txtRespuesta;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
